Fix/repeated code
SwedbankPay/design.swedbankpay.com pull request #424
Opened 2021-01-19 15:16 UTC by PhungNg

## Description

Improved code where repeated HTML occurred. Moved the data to a seperated list and looped through instead

## Motivation and Context
Looks silly

## How Has This Been Tested?
Ran all existing test, and updated snaps

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-01-22 11:50 UTC, pthoang requested changes
Very much improved code! 👍  Just some suggestions that can improve it further

2021-01-22 11:50 UTC, pthoang commented on src/App/Home/constants.js
> +export const entryCards = [
Maybe use information found in `routes` to do this (specifically `routes/all`) to avoid duplicates?

2021-01-22 11:50 UTC, pthoang commented on src/App/GettingStarted/getting-started/ForDevelopers/constants.js
> +export const discoverMore = [
Might be a good idea to find a way to get URLs from one single source, to avoid dead links in case of route changes

2021-01-22 11:50 UTC, pthoang commented on src/App/Home/constants.js
> +        title: "Introducing the the new codeview component",
"the the" should be fixed

2021-01-29 09:07 UTC, VikingTristan commented on src/App/GettingStarted/getting-started/ForDevelopers/constants.js
> +const [, identity, components, utilities] = routes;
Interesting

2021-01-29 09:26 UTC, VikingTristan commented on src/App/Home/index.js
> +                                    <i className={`material-icons-outlined ${route.icon.rotate && "rotate-icon"}`}>{route.icon.name}</i>
rotate the little bulb, lmao

2021-01-29 09:29 UTC, VikingTristan commented on src/App/Home/index.js
> +                        <div className="px-0 pb-2">Version {log.version}</div>
Version vs Ver. vs V. etc.
There seems to be some inconsistencies on how to write these, 🤷

2021-01-29 09:44 UTC, VikingTristan approved these changes
Looking good!

2021-01-29 09:56 UTC, merged