Node package and more!
SwedbankPay/design.swedbankpay.com pull request #514
Opened 2021-07-22 19:18 UTC by VikingTristan

- Rework and update webpack and pave way for publishing a node package
- Update Design Guide script itself to be easier to import from others.
- Make our hosted Design Guide slightly different ( the "cdn" one )
  - The cdn version will autoload itself, the imported one from node modules will not.
- Update jest with new major and all tests accordingly
- Upgrade all node packages except chart.js ( it has a new major and requires a PR by itself )
- Add a workflow for publishing a node package whenever there is a new tag and version in the package.json.
- Add new documentation for installation and usage of new node package.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-07-22 20:00 UTC, asbjornu requested changes
![Wonderful!](https://user-images.githubusercontent.com/12283/126701973-683bd79a-a1be-4678-97da-6c341aef8753.gif)

2021-07-23 07:21 UTC, VikingTristan commented on .github/workflows/node-package.yml
> +            ${{ runner.os }}-node-
ooooooo, very nice.

2021-07-23 07:22 UTC, VikingTristan commented on README.md
> +npm i @swedbankpay/design.swedbankpay.com
agree

2021-07-23 07:23 UTC, VikingTristan commented on README.md
> +When using the node package you also need to host assets such as fonts and icons. Copy the files at `@swedbankpay/design.swedbankpay.com/dist/designguide` to your static files.
Hmm, interesting...

2021-07-23 07:29 UTC, VikingTristan commented on package.json
> +  "version": "6.1.0",
that's an interesting idea

2021-07-23 07:32 UTC, VikingTristan commented on src/App/ComponentsDocumentation/components/Charts/Introduction/index.js
> -const styleUrl = `${window.location.origin + basename}styles/dg-style.css`;
As I was updating the url to point to new css files, I noticed that the CSS isn't being used at all in charts. So I removed it entirely.

2021-08-16 11:17 UTC, VikingTristan commented on README.md
> +When using the node package you also need to host assets such as fonts and icons. Copy the files at `@swedbankpay/design.swedbankpay.com/dist/designguide` to your static files.
I wrote your suggestion as a suggestion in the doc :)

2021-08-16 11:18 UTC, VikingTristan commented on package.json
> +  "version": "6.1.0",
very interesting, but to be honest I'm not entirely sure how to proceed with this and I would like to perhaps do it in its own PR in the future

2021-08-16 11:21 UTC, asbjornu commented on package.json
> +  "version": "6.1.0",
Sure, good idea.

2021-08-16 11:39 UTC, asbjornu approved these changes
👏🏼 👏🏼 👏🏼

2021-08-16 12:19 UTC, VikingTristan commented
@asbjornu gah, noticed some minor rendering bugs with new imports on a few pages.
incoming fixes throughout the day

2021-08-16 13:22 UTC, merged