Feature/wcag componentpreview fieldset
SwedbankPay/design.swedbankpay.com pull request #610
Opened 2022-01-27 14:59 UTC by eskilsen

## Description

From FUNKA audit we found out the componentpreview didn't use html semantics. Options menu is now updated to legend and fieldset instead of h4 and divs. 

Task: https://payexjira.atlassian.net/jira/software/c/projects/SWED/boards/312?modal=detail&selectedIssue=SWED-1051

## How Has This Been Tested?

Ran all existing tests and update snapshots. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-02-07 11:23 UTC, PhungNg reviewed
Very nice! 🏅 
Just a small change on the Dropdown section. And the filter part

2022-02-07 11:23 UTC, PhungNg commented on src/App/routes/patterns.js
> +                statusBadges: ["new"]
😅

2022-02-07 11:24 UTC, PhungNg requested changes
Forgot to request a change 😅

2022-02-07 15:05 UTC, eskilsen commented on src/App/routes/patterns.js
> +                statusBadges: ["new"]
😠

2022-02-14 09:48 UTC, PhungNg approved these changes
Noice👍

2022-02-14 13:59 UTC, merged