Feature/update pagination
SwedbankPay/design.swedbankpay.com pull request #628
Opened 2022-02-21 14:33 UTC by eskilsen

Update of pagination script, component and documentation page. 
## Description
New documentation, new style, more userfriendly pagination script.  

## How Has This Been Tested?

Created tests suitable for pagination component.
Render tests for pagination doc page. 
Tests for pagination script. 
Update snapshots. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-02-22 16:35 UTC, asbjornu requested changes
👏🏼

2022-02-22 16:35 UTC, asbjornu commented on src/App/ComponentsDocumentation/components/Pagination/index.js
> +        <p>Remember to add <CodeTags type="primary" code={"<link rel=\"prev\" href=\"prev_page\">"}/> and <CodeTags type="primary" code={"<link rel=\"next\" href=\"next_page\">"}/> in <CodeTags type=
```suggestion
        <p>Consider adding <CodeTags type="primary" code={"<link rel=\"…\" href=\"…\">"}/> to the <CodeTags type="primary" code={"<head>"}/> element of your HTML page. These links are used to indicate the relationships between a sequence of pages to web browsers and search engines. Link relations to consider adding are <CodeTags type="primary" code={"first"}/>, <CodeTags type="primary" code={"last"}/>, <CodeTags type="primary" code={"next"}/> and <CodeTags type="primary" code={"prev"}/>.</p>
```

2022-02-22 16:35 UTC, asbjornu commented on src/App/ComponentsDocumentation/components/Pagination/index.js
> +        <h3>Pagination attributes</h3>
```suggestion
        <h3>Link relations</h3>
```

2022-02-22 16:35 UTC, asbjornu commented on src/App/ComponentsDocumentation/components/Pagination/index.js
> +        <p>Our pagination component works without a script, so the styling is still working where Javascript is prohibited. But where it is allowed, and where you do not want to spend time banging yo
```suggestion
        <p>Our pagination component works without a script, so the styling is still working where JavaScript is prohibited. But where it is allowed, and where you do not want to spend time banging your head to figure out the algorithm, the Design Guide provides a reference implementation! <CodeTags type="secondary" code="dg.paginate(pages, currentActive)"/>. The script takes in two arguments; <CodeTags type="primary" code="pages"/> and <CodeTags type="primary" code="currentActive"/>, where <CodeTags type="primary" code="pages"/> is total pages and <CodeTags type="primary" code="currentActive"/> is the current active page.</p>
```

2022-02-22 16:35 UTC, asbjornu commented on src/App/ComponentsDocumentation/components/Pagination/index.js
> +            &#123;page: 10, current: false&#125;]
```suggestion
                {"//expected output:"}{"\n"}
            [
                &#123;page: 1, current: false&#125;,{"\n"}
                &#123;page: null, current: false&#125;,{"\n"}
                &#123;page: 4, current: false&#125;,{"\n"}
                &#123;page: 5, current: true&#125;,{"\n"}
                &#123;page: 6, current: false&#125;,{"\n"}
                &#123;page: null, current: false&#125;,{"\n"}
                &#123;page: 10, current: false&#125;
            ]
```

2022-02-22 16:35 UTC, asbjornu commented on src/App/ComponentsDocumentation/components/Pagination/index.js
> +            Pagination is used to divide large amounts of content into separate pages and allows the user to navigate to next or previous pages.
```suggestion
            Pagination is used to divide large amounts of content into separate pages and allows the user to navigate to the next or previous pages.
```

2022-02-22 16:35 UTC, asbjornu commented on src/scripts/main/pagination/index.js
> +        throw "CurrentActive can not be greater then total pages.";
```suggestion
        throw "CurrentActive can not be greater than total pages.";
```

2022-02-22 16:35 UTC, asbjornu commented on src/scripts/main/pagination/index.js
> +        throw ("CurrentActive must be greater then 0");
```suggestion
        throw ("CurrentActive must be greater than 0");
```

2022-02-23 09:28 UTC, PhungNg approved these changes
Tears of joy!! 😭

2022-02-23 10:31 UTC, asbjornu requested changes
A very minor nit, then this is ready for 🚀❗

2022-02-23 10:31 UTC, asbjornu commented on src/App/ComponentsDocumentation/components/Pagination/index.js
> +        <p>While the pagination component supports an infinite amount of pages, it is difficult to deliver a good user experience when the number of pages exceeds 10. In circumstances where it is dif
I think this reads a bit better.

```suggestion
        <p>While the pagination component supports an infinite amount of pages, it is difficult to deliver a good user experience when the number of pages exceeds 10. In circumstances where it is difficult for a user to find what they are looking for within the first few search results, they may develop bad habits (such as finding what they are looking for on page 13, search result 5). To mitigate this, more advanced solutions than a single search field should be considered, such as categorization, labels, faceted search, etc.</p>
```

2022-02-23 11:56 UTC, asbjornu approved these changes
![Awesome!](https://user-images.githubusercontent.com/12283/155314849-417d7051-8394-468d-a8a5-15ed720f685e.gif)

2022-02-23 12:18 UTC, merged