Feature/update input field hint text
SwedbankPay/design.swedbankpay.com pull request #652
Opened 2022-03-28 14:20 UTC by eskilsen

## Description

Update input field group with hint texts. Tooltips is out, different hint texts are in. Mainly to be wcag complient. 
Also updated documentation with more examples and a more crisp look with tabs in componentpreview. 

## Motivation and Context

## How Has This Been Tested?

Ran all existing tests and updated/removed tests. 
## Screenshots (if appropriate):
Before: 
<img width="688" alt="image" src="https://user-images.githubusercontent.com/21359433/160418473-6f5011a8-c847-4207-b0e3-eafb8ea334d2.png">
Now:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/21359433/160418356-5b075f45-7b81-4811-b8c7-ab660a31d6d6.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2022-04-05 12:31 UTC, PhungNg requested changes
Some few changes before we can merge !
Otherwise..Great job ☜(ﾟヮﾟ☜)

2022-04-08 08:33 UTC, eskilsen commented on src/App/ComponentsDocumentation/components/InputField/constants.js
> +            component: <InputGroup type="textarea" label="Label" />,
Hmm... The hint text is there to provide essential information for the user.. If something is disabled they should still be able to read the info.. Dont'cha agree? Maybe the info can help the users make the components enabled again? 🤓

2022-04-20 08:38 UTC, PhungNg requested changes
Cooool! Just one small thing :) 🎖️

2022-04-20 08:38 UTC, PhungNg commented on src/App/ComponentsDocumentation/components/Select/constants.js
>                              }
As we discussed :)

![image](https://user-images.githubusercontent.com/44967773/164182940-a5df25b5-d02b-4c11-baa8-3781f427c1da.png)

2022-04-20 11:22 UTC, PhungNg approved these changes
Niceee! ⭐

2022-04-20 11:29 UTC, merged