Feature/update error icons and placement in form components
SwedbankPay/design.swedbankpay.com pull request #698
Opened 2022-06-21 12:00 UTC by eskilsen

Update error icons and error messages to be more wcag compliant. 
Users with color disabilities would have struggled or better yet, not noticed the old errors. 
This is now fixed. 

## Motivation and Context

## How Has This Been Tested?

Updated tests for some components and updated snapshots. 
## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/21359433/174793970-be476d47-a98d-40e9-9461-6175fada6829.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [X] I have updated the **CHANGELOG** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

## Review instructions
[Review instructions](../REVIEW_INSTRUCTIONS.md)

2022-06-21 12:41 UTC, PhungNg requested changes
A few things to change. Also, the Select component also need an error icon inside the input

2022-06-21 12:41 UTC, PhungNg commented on src/App/components/FormComponents/Checkbox.js
> +                    {errorMessage && <><div className="help-block"><i className="material-icons">error</i>{errorMessage}</div>{"\n"}</>}
According to figma, the icon should be a triangle 
![image](https://user-images.githubusercontent.com/44967773/174799459-13e2c673-b80b-45ec-abad-6375bf036054.png)

2022-06-21 12:41 UTC, PhungNg commented on src/App/components/FormComponents/Radio.js
> +                        {errorMessage && <><div className="help-block"><i className="material-icons">error</i>{errorMessage}</div>{"\n"}</>}
Triangle icon in figma
![image](https://user-images.githubusercontent.com/44967773/174799724-35d44731-244d-4a47-81b0-04617a3b8b23.png)

2022-06-21 12:41 UTC, PhungNg commented on src/App/components/InputGroup/index.js
> +            {errorMessage && <><div className="help-block"><i className="material-icons">error</i>{errorMessage}</div>{"\n"}</>}
The icon should be inside the field, and not before the error message. Like this:
![image](https://user-images.githubusercontent.com/44967773/174800658-430bcf22-e351-48b3-ae35-9f765cc3e23c.png)

This also removed the error icon from input field
![image](https://user-images.githubusercontent.com/44967773/174800731-90561425-7790-42b8-a770-a56dfd5c1e4d.png)

2022-06-21 12:41 UTC, PhungNg commented on src/less/components/validation.less
> -        }
Why are this removed?

2022-06-21 13:27 UTC, eskilsen commented
I think there are some misunderstandings regarding which figma file to follow 😅 
I followed this https://www.figma.com/file/1OlqVHKlbnyl63sYkaL2WI/%C3%85.-Pattern%2FForms?node-id=122%3A3414 which was written in the jira-task https://payexjira.atlassian.net/jira/software/c/projects/SWED/boards/312?modal=detail&selectedIssue=SWED-1732

2022-06-22 06:41 UTC, PhungNg commented
Ok, good thing we got it straight at least :)
Not much to say other then good job then! :D

2022-06-22 06:41 UTC, PhungNg approved these changes
Woho! :D

2022-06-22 06:48 UTC, merged