Feature/update button designs
SwedbankPay/design.swedbankpay.com pull request #716
Opened 2022-08-03 09:13 UTC by eskilsen

Update design of buttons based on figma: https://www.figma.com/file/ytZGjTEFZS5ZIxB5Q7nfQp/2.-Components?node-id=7384%3A4435. Ticket: https://payexjira.atlassian.net/jira/software/c/projects/SWED/boards/312?modal=detail&selectedIssue=SWED-237

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have updated the **CHANGELOG** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

## Review instructions
[Review instructions](../REVIEW_INSTRUCTIONS.md)

2022-08-15 08:53 UTC, PhungNg requested changes
Good work bro!
But seems like you missed some small changes!
Good luck fixing them! Cause by the time you read this, Im long gone friend 😭💔

2022-08-15 08:53 UTC, PhungNg commented on src/App/components/Button/index.js
> +            {icon && !iconAfter ? <><i className="material-icons-outlined" aria-hidden="true">{icon}</i>{"\n\t"}</> : null}
Pixel-jocker incoming!
Margin on left and right side of icon are not equal
![image](https://user-images.githubusercontent.com/44967773/184600986-d5e51a97-36d5-4edd-a010-2b4d9f403a3a.png)

2022-08-15 08:53 UTC, PhungNg commented on src/less/components/button.less
>      &:hover,
Probably not this line, but according to Figma, the hover color should be #FBDD91 and not #FFDF88.
The same applies to the focus state.

2022-08-15 08:53 UTC, PhungNg commented on src/less/components/button.less
>      &:hover,
The box shadow for when the Button is active, should now be 1px, with color #FBDD91.

2022-08-15 08:53 UTC, PhungNg commented on src/less/components/button.less
Buttons with loading state should not be able to receive an active state
![image](https://user-images.githubusercontent.com/44967773/184603171-bcccadef-0a72-45ce-bfd8-70993f6f48b6.png)

2022-08-15 08:53 UTC, PhungNg commented on src/less/components/button.less
The After icon size should stay the same regardless of buttons size.
![image](https://user-images.githubusercontent.com/44967773/184603898-09071a98-7b04-4e99-9ac6-0cbd49c1b328.png)

2022-08-15 08:53 UTC, PhungNg commented on src/less/components/button.less
Executive-destructiv button has the wrong box-shadow color. Should be #EE5058
![image](https://user-images.githubusercontent.com/44967773/184604760-b0d2182d-3edd-4eca-bc38-6551b0ca5015.png)

2022-09-05 07:54 UTC, m-lilja approved these changes
LGTM

2022-09-05 08:36 UTC, merged