pfe-199: Changed color for brand-seconday-hover, btn-active-color and…
SwedbankPay/design.swedbankpay.com pull request #940
Opened 2024-01-22 10:39 UTC by Fastanton

… btn-secondary-hover

## Description

the colors for brand-secondary-hover, --btn-active-color, --btn-secondary-hover was wrong. And need to change color. 

## Motivation and Context

The problems is solved with the corrections.

## How Has This Been Tested?

Visual review sent to designer.

## Screenshots (if appropriate):

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have read the **CONTRIBUTING** document.
-   [ ] I have updated the **CHANGELOG** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

## Review instructions

[Review instructions](../REVIEW_INSTRUCTIONS.md)

2024-01-22 10:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SwedbankPay/design.swedbankpay.com?pullRequest=940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SwedbankPay/design.swedbankpay.com?pullRequest=940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SwedbankPay/design.swedbankpay.com?pullRequest=940) it.</sub>

2024-01-22 11:28 UTC, goldenraphti commented on src/less/variables-payex.less
> +	--brand-secondary-hover: #707070;
remember to keep "LESS vars" and "Pure CSS vars, i.e. custom properties" in sync 😉

2024-01-22 11:28 UTC, goldenraphti commented on src/less/components/payex/button.less
> +			border: 1px solid @brand-primary;
remember to try to use CSS custom properties when possible and when it is not requiring too much work 😉

2024-01-22 13:51 UTC, goldenraphti commented on src/less/components/payex/button.less
> +			border: 1px solid @brand-primary;
```suggestion
			border: 1px solid var(--brand-primary);
```

2024-01-22 13:52 UTC, goldenraphti requested changes

2024-01-22 13:57 UTC, goldenraphti commented on src/less/variables-payex.less
> +	--btn-secondary-hover: var(--soft-brown, #707070);
```suggestion
	--btn-secondary-hover: var(--brand-secondary-hover, #707070);
```

2024-01-22 14:00 UTC, goldenraphti approved these changes
Approooooved 💫✨💜

2024-01-23 08:12 UTC, Joelhagg approved these changes
Nicely done! If @goldenraphti give the thumbs up, so do I 👌

2024-01-23 09:38 UTC, merged